# GENERATED from packages.tsv by packages/gen-brewfile.sh — DO NOT EDIT.
# Edit the macos column in packages.tsv, then re-run packages/gen-brewfile.sh.

brew "git"
brew "mise"
brew "kubectl"
brew "derailed/k9s/k9s"
brew "kubectx"
brew "awscli"
brew "azure-cli"
cask "google-cloud-sdk"
brew "podman"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "fzf"
brew "ripgrep"
brew "jq"
brew "yq"
brew "tldr"
cask "brave-browser"
cask "google-chrome"
cask "obsidian"
cask "visual-studio-code"
cask "slack"
cask "discord"
cask "bitwarden"
cask "clickup"
cask "claude-code"
cask "alt-tab"
cask "rectangle"
